### ISSUE TITLE
你好，element-plus有一个提交，导致错误了，麻烦尽快看看

### ISSUE THREAD

**Issue by 406087475** [Liao-js/Liao-js#1]
你好，element-plus有一个提交，导致错误了，麻烦尽快看看

**Comment by 406087475** [comment]
const columnIndex = columnConfig.value.getColumnIndex()  这个代码，columnConfig.value.getColumnIndex没有判空，导致报错，执行不下去

**Comment by Liao-js** [comment]
> const columnIndex = columnConfig.value.getColumnIndex() 这个代码，columnConfig.value.getColumnIndex没有判空，导致报错，执行不下去

你好，能提供最小复现吗？

**Comment by 406087475** [comment]
不好意思，因为项目比较大，短时间没法拆出具体场景，我明天再细看下；

**Comment by Liao-js** [comment]
还有有关 

> 不好意思，因为项目比较大，短时间没法拆出具体场景，我明天再细看下；

你好，有 element 相关的问题，在 element 项目中提 issue 就行的

**Comment by Liao-js** [comment]
因为在 onMounted 就已经赋值了
```
onMounted(() => {
      const parent = columnOrTableParent.value
      const children = isSubColumn.value
        ? parent.vnode.el.children
        : parent.refs.hiddenColumns?.children
      const getColumnIndex = () =>
        getColumnElIndex(children || [], instance.vnode.el)
      columnConfig.value.getColumnIndex = getColumnIndex
      const columnIndex = getColumnIndex()
      columnIndex > -1 &&
        owner.value.store.commit(
          'insertColumn',
          columnConfig.value,
          isSubColumn.value ? parent.columnConfig.value : null,
          updateColumnOrder
        )
    })
```

**Comment by 406087475** [comment]
明白的，主要是比较急，所以才直接来找你，主要场景是在 vuedraggable 中使用了表格组件，你发的代码我也看到了，确实一直有赋值，但是出错前的打印，确实没有这个方法的

**Comment by 406087475** [comment]
因为我们之前用的是2.6.3版本，没有这次的提交，是正常的，但是更新到2.7.2后就直接挂了

**Comment by Liao-js** [comment]
好的，因为就算我提交了修复，也是需要项目负责人进行代码合并的

**Comment by 406087475** [comment]
明白，打扰了
let columnIndex = columnConfig.value?.getColumnIndex
columnIndex = columnIndex ? columnIndex() : -1

我改成这样后，倒是临时修复了，期待你们的修复版本
